spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mongs123
    url: jdbc:mysql://master:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
server:
  port: 8080
